# Generated by Django 3.1.3 on 2021-03-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patment_mode', models.CharField(max_length=20)),
                ('acc_no', models.IntegerField()),
                ('IFSC', models.CharField(max_length=30)),
                ('cvv', models.IntegerField()),
            ],
        ),
    ]
