# Generated by Django 3.1.3 on 2021-03-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
    ]
