# Generated by Django 3.1.3 on 2021-03-08 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20210306_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='acc_no',
            new_name='card_no',
        ),
    ]
