# Generated by Django 3.1.3 on 2021-03-03 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('bed_type', models.CharField(choices=[('singlebed', 'singlebed'), ('doublebed', 'doublebed')], max_length=20)),
                ('room_type', models.CharField(choices=[('A/C', 'A/C'), ('non_A/c', 'non_A/C')], max_length=20)),
                ('guests', models.IntegerField()),
                ('food', models.CharField(choices=[('want', 'want'), ('dontwant', 'dontwant')], max_length=20)),
                ('amount', models.IntegerField()),
                ('status', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
