# Generated by Django 3.1.3 on 2021-03-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='guests',
            new_name='guest',
        ),
    ]
